🦈 Update latex.yml

diff --git a/.github/workflows/latex.yml b/.github/workflows/latex.yml
--- a/.github/workflows/latex.yml
+++ b/.github/workflows/latex.yml
@@ -20,10 +20,10 @@ jobs:
             echo "changed=false" >> $GITHUB_OUTPUT
           fi
 
-      - name: Check for changes in main.tex
-        id: check_main
+      - name: Check for changes in ml.tex
+        id: check_ml
         run: |
-          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^main\.tex$'; then
+          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^ml\.tex$'; then
             echo "changed=true" >> $GITHUB_OUTPUT
           else
             echo "changed=false" >> $GITHUB_OUTPUT
@@ -36,20 +36,20 @@ jobs:
           root_file: dl.tex
           args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
 
-      - name: Compile main.tex
-        if: steps.check_main.outputs.changed == 'true'
+      - name: Compile ml.tex
+        if: steps.check_ml.outputs.changed == 'true'
         uses: xu-cheng/latex-action@v3
         with:
-          root_file: main.tex
+          root_file: ml.tex
           args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
 
       - name: Get current date
         id: date
-        if: steps.check_dl.outputs.changed == 'true' || steps.check_main.outputs.changed == 'true'
+        if: steps.check_dl.outputs.changed == 'true' || steps.check_ml.outputs.changed == 'true'
         run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
 
       - name: Upload PDFs to pdfs branch
-        if: steps.check_dl.outputs.changed == 'true' || steps.check_main.outputs.changed == 'true'
+        if: steps.check_dl.outputs.changed == 'true' || steps.check_ml.outputs.changed == 'true'
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
@@ -70,11 +70,11 @@ jobs:
             fi
           fi
           
-          if [ "${{ steps.check_main.outputs.changed }}" == "true" ]; then
-            cp main.pdf . || echo "main.pdf not found"
-            if [ -f main.pdf ]; then
-              git add main.pdf
-              git commit -m "📖 Update main.pdf - ${{ steps.date.outputs.date }}"
+          if [ "${{ steps.check_ml.outputs.changed }}" == "true" ]; then
+            cp ml.pdf . || echo "ml.pdf not found"
+            if [ -f ml.pdf ]; then
+              git add ml.pdf
+              git commit -m "📖 Update ml.pdf - ${{ steps.date.outputs.date }}"
             fi
           fi
           
@@ -86,7 +86,7 @@ jobs:
           fi
 
       - name: Upload PDFs as artifacts
-        if: steps.check_dl.outputs.changed == 'true' || steps.check_main.outputs.changed == 'true'
+        if: steps.check_dl.outputs.changed == 'true' || steps.check_ml.outputs.changed == 'true'
         uses: actions/upload-artifact@v4
         with:
           name: PDFs
